# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_username', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=200)),
                ('user_first_name', models.CharField(max_length=20)),
                ('user_last_name', models.CharField(max_length=100)),
                ('user_location', models.CharField(choices=[('Auto', 'Auto'), ('Aasfontein', 'Aasfontein'), ('Abramskraal', 'Abramskraal'), ('Acornhoek', 'Acornhoek'), ('Albertina', 'Albertina'), ('Alexander Bay', 'Alexander Bay'), ('Aliwal North', 'Aliwal North'), ('Alkmaar', 'Alkmaar'), ('Alldays', 'Alldays'), ('An-de-Waterkant', 'An-de-Waterkant'), ('Angalacane', 'Angalacane'), ('Arcadia', 'Arcadia'), ('Ardmore', 'Ardmore'), ('Barkly East', 'Barkly East'), ('Barrys Kop', 'Barrys Kop'), ('Bayete', 'Bayete'), ('Beaufort West', 'Beaufort West'), ('Bergwater', 'Bergwater'), ('Berlin', 'Berlin'), ('Bethal', 'Bethal'), ('Bethlehem', 'Bethlehem'), ('Bhokweni', 'Bhokweni'), ('Bierberg', 'Bierberg'), ('Big Bay', 'Big Bay'), ('Bloedrivier', 'Bloedrivier'), ('Bloemfontein', 'Bloemfontein'), ('Bloemhof', 'Bloemhof'), ('Bo-Kaap', 'Bo-Kaap'), ('Bottelary', 'Bottelary'), ('Brospan', 'Brospan'), ('Bultfontein', 'Bultfontein'), ('Calvinia', 'Calvinia'), ('Cape Columbine', 'Cape Columbine'), ('Cape Point', 'Cape Point'), ('Cape Town', 'Cape Town'), ('Carnarvon', 'Carnarvon'), ('Cedara', 'Cedara'), ('Cradock', 'Cradock'), ('Dagbreek', 'Dagbreek'), ('Darnall', 'Darnall'), ('Dassen Island', 'Dassen Island'), ('De Aar', 'De Aar'), ('Dinkung', 'Dinkung'), ('Dohne', 'Dohne'), ('Duiwelskloof', 'Duiwelskloof'), ('Dullstroom', 'Dullstroom'), ('Durban', 'Durban'), ('Dwarsloop', 'Dwarsloop'), ('East London', 'East London'), ('Edinburgh of the Seven Seas', 'Edinburgh of the Seven Seas'), ('Elliot', 'Elliot'), ('Ellisras', 'Ellisras'), ('Empangeni', 'Empangeni'), ('Ermelo', 'Ermelo'), ('Estcourt', 'Estcourt'), ('Fauresmith', 'Fauresmith'), ('Fort Beaufort', 'Fort Beaufort'), ('Fraserburg', 'Fraserburg'), ('Ga-Malepe', 'Ga-Malepe'), ('Gemsbokhoek', 'Gemsbokhoek'), ('George', 'George'), ('Germiston', 'Germiston'), ('Goodhouse', 'Goodhouse'), ('Graaff-Reinet', 'Graaff-Reinet'), ('Grahamstown', 'Grahamstown'), ('Greytown', 'Greytown'), ('Groblersdal', 'Groblersdal'), ('Hoedspruit', 'Hoedspruit'), ('Hondeklipbaai', 'Hondeklipbaai'), ('Ixopo', 'Ixopo'), ('Jamestown', 'Jamestown'), ("Jeffrey's Bay", "Jeffrey's Bay"), ('Johannesburg', 'Johannesburg'), ('Joubertina', 'Joubertina'), ('Kathu', 'Kathu'), ('Kgamatha', 'Kgamatha'), ('Kimberley', 'Kimberley'), ('Klerksdorp', 'Klerksdorp'), ('Knysna', 'Knysna'), ('Koppies', 'Koppies'), ('Kuruman', 'Kuruman'), ('La Mercy', 'La Mercy'), ('Ladysmith', 'Ladysmith'), ('Laingsburg', 'Laingsburg'), ('Lamberts Bay', 'Lamberts Bay'), ('Langebaan', 'Langebaan'), ('Langebaanweg', 'Langebaanweg'), ('Lanseria', 'Lanseria'), ('Levubu', 'Levubu'), ('Lichtenburg', 'Lichtenburg'), ('Linton', 'Linton'), ('Lydenburg', 'Lydenburg'), ('Maclear', 'Maclear'), ('Madikwe Game Reserve', 'Madikwe Game Reserve'), ('Malmesbury', 'Malmesbury'), ('Mara', 'Mara'), ('Margate', 'Margate'), ('Marion Island', 'Marion Island'), ('Marken', 'Marken'), ('Marnitz', 'Marnitz'), ('Matatiele', 'Matatiele'), ('Mmabatho', 'Mmabatho'), ('Mookane', 'Mookane'), ('Mossel Bay', 'Mossel Bay'), ('Mount Edgecombe', 'Mount Edgecombe'), ('Mtubatuba', 'Mtubatuba'), ('Mtunzini', 'Mtunzini'), ('Nelspruit', 'Nelspruit'), ('Newcastle', 'Newcastle'), ('Ottosdal', 'Ottosdal'), ('Oudtshoorn', 'Oudtshoorn'), ('Paarl', 'Paarl'), ('Paddock', 'Paddock'), ('Patensie', 'Patensie'), ('Phalaborwa', 'Phalaborwa'), ('Piet Retief', 'Piet Retief'), ('Pietermaritzburg', 'Pietermaritzburg'), ('Pietersburg', 'Pietersburg'), ('Pinetown', 'Pinetown'), ('Plettenberg Bay', 'Plettenberg Bay'), ('Pofadder', 'Pofadder'), ('Pomfret', 'Pomfret'), ('Pongola', 'Pongola'), ('Ponzela', 'Ponzela'), ('Port Alfred', 'Port Alfred'), ('Port Edward', 'Port Edward'), ('Port Elizabeth', 'Port Elizabeth'), ('Port Nolloth', 'Port Nolloth'), ('Port Shepstone', 'Port Shepstone'), ('Porterville', 'Porterville'), ('Postmasburg', 'Postmasburg'), ('Potchefstroom', 'Potchefstroom'), ('Potgietersrus', 'Potgietersrus'), ('Prieska', 'Prieska'), ('Queenstown', 'Queenstown'), ('Razao', 'Razao'), ('Richards Bay', 'Richards Bay'), ('Robertson', 'Robertson'), ('Rustenburg', 'Rustenburg'), ('Sehlabathebe', 'Sehlabathebe'), ('Sezela', 'Sezela'), ('Skukuza', 'Skukuza'), ('Somerset East', 'Somerset East'), ('Standerton', 'Standerton'), ('Stanger', 'Stanger'), ('Strand', 'Strand'), ('Struisbaai', 'Struisbaai'), ('Taung', 'Taung'), ('Thabazimbi', 'Thabazimbi'), ('Thohoyandou', 'Thohoyandou'), ('Tshipise', 'Tshipise'), ('Twee Rivieren', 'Twee Rivieren'), ('Uitenhage', 'Uitenhage'), ('Ulundi', 'Ulundi'), ('Umtata', 'Umtata'), ('Umzimvubu', 'Umzimvubu'), ('Upington', 'Upington'), ('Van Zylsrus', 'Van Zylsrus'), ('Ventersdorp', 'Ventersdorp'), ('Venterstad', 'Venterstad'), ('Vioolsdrif', 'Vioolsdrif'), ('Vredendal', 'Vredendal'), ('Vryburg', 'Vryburg'), ('Vyeboom', 'Vyeboom'), ('Warmbaths', 'Warmbaths'), ('Welkom', 'Welkom'), ('Wepener', 'Wepener'), ('Wevedeen', 'Wevedeen'), ('Willowmore', 'Willowmore'), ('Witbank', 'Witbank'), ('Worcester', 'Worcester')], max_length=200)),
                ('user_apps', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='Registered Date')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_code', models.CharField(default='1', max_length=100)),
                ('weather_type_code', models.CharField(default='trdw', max_length=3)),
                ('weather_area', models.CharField(max_length=100)),
                ('weather_date', models.DateField(verbose_name='Published Date')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='weather_byte_app.MyUsers')),
            ],
        ),
        migrations.CreateModel(
            name='Weather_Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_comp_datetime', models.DateTimeField(verbose_name='Published Date')),
                ('weather_comp_icon_url', models.CharField(max_length=200)),
                ('weather_comp_min_temp', models.CharField(max_length=10)),
                ('weather_comp_max_temp', models.CharField(max_length=10)),
                ('weather_comp_rain', models.CharField(max_length=100)),
                ('weather_comp_description', models.CharField(max_length=200)),
                ('weather_comp_label', models.CharField(max_length=100)),
                ('weather_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='weather_byte_app.Weather')),
            ],
        ),
        migrations.AddIndex(
            model_name='weather_component',
            index=models.Index(fields=['weather_id', 'weather_comp_datetime'], name='idxwc1'),
        ),
        migrations.AddIndex(
            model_name='weather',
            index=models.Index(fields=['app_code', 'user_id', 'weather_date', 'weather_area', 'weather_type_code'], name='idxw1'),
        ),
    ]
