# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_byte_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_component',
            name='weather_comp_datetime',
            field=models.CharField(max_length=200),
        ),
    ]
